# Generated by Django 5.0 on 2023-12-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CarSpecs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("car_brand", models.CharField(max_length=50)),
                ("car_model", models.CharField(max_length=100)),
                ("production_year", models.CharField(max_length=10)),
                ("car_body", models.CharField(max_length=100)),
                ("car_engine_type", models.CharField(max_length=50)),
                ("car_fuel", models.CharField(max_length=50)),
                ("car_engine_cc", models.CharField(max_length=50)),
            ],
        ),
    ]
